run:
  timeout: 5m

  build-tags:
    - e2e

linters:
  enable:
    - asciicheck
    - errorlint
    - gosec
    - prealloc
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unparam
  disable:
    - errcheck
